Repository FIRSTPLATO/antco, pull requests merged in 2020-10, with the labels that each got.

#1 Enhancement docs with needed information listed
  1.jpg
  README.md
  README_en.md
Labels: documentation, hacktoberfest-accepted

#2 aco.js + map to view + some ui and config
  antco/configdb.php
  antco/db/.list
  antco/ui/.list
  antco/ui/img/.list
  antco/ui/img/logo.png
  map/aco.js
  map/map.php
Labels: enhancement, hacktoberfest-accepted

#3 add and update several new files
  antco/alternatif.php
  antco/dashboard.php
  antco/profile.php
Labels: enhancement, hacktoberfest-accepted, major update

#4 rute - jadwal - lokasi - analisa
  antco/analisa.php
  antco/jadwal.php
  antco/lokasi.php
  antco/rute.php
Labels: enhancement, hacktoberfest-accepted, major update
